# Generated by cpp11: do not edit by hand

uno_version <- function() {
  .Call(`_Uno_uno_version`)
}

uno_solve <- function(n, lb, ub, sense, obj, grad, m, cl, cu, cons, jac_rows, jac_cols, jac, hess_rows, hess_cols, hess, x0, preset, base_indexing, verbose) {
  .Call(`_Uno_uno_solve`, n, lb, ub, sense, obj, grad, m, cl, cu, cons, jac_rows, jac_cols, jac, hess_rows, hess_cols, hess, x0, preset, base_indexing, verbose)
}
